### ISSUE TITLE
Middleware: Data Aggregation

### ISSUE THREAD

**Issue by lolandrew1** [CMU-313/fall22-hw3-h1#5]
Implement functions to perform data aggregation and return the results 

estimated time: 4 days
Implementing the data aggregation functionality will be the bulk of the middleware changes. We will have to perform a variety of aggregations and add new methods to the API. 

dependencies: backend changes, CRUD functions

implementation plan: We will first make sure that we are retrieving all documents and store certain numerical fields in a data structure. Once that data is retrieved and stored, we will pass it to several data aggregation functions, testing each one to ensure correctness.

**Comment by chloec2** [comment]
completed in frontend
